# Generated by Django 6.0.1 on 2026-01-26 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADManagerX', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapsettings',
            name='server_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='ldapsettings',
            name='user_search_base',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
