# Generated by Django 6.0.1 on 2026-01-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADManagerX', '0002_ldapsettings_server_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapsettings',
            name='base_dn',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='computers_ou_dn',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='groups_ou_dn',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='safe_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='upn_suffix',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='users_ou_dn',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
