# Generated by Django 5.1.1 on 2026-05-02 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ADManagerX', '0003_ldapsettings_base_dn_ldapsettings_computers_ou_dn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpdeskprofile',
            name='domain_permissions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='domain_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ldapsettings',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
